"""empty message

Revision ID: 38308c4ca9ae
Revises: c1e22810ae9c
Create Date: 2024-04-08 22:11:12.615464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38308c4ca9ae'
down_revision = 'c1e22810ae9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    # ### end Alembic commands ###
